id: I4BB0E7C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:47:32+00:00'
last_modified: '2022-06-07T12:33:42.039378+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17591
  title: དཔལ་ཀུན་རིག་གི་ཆོ་ག་ཐམས་ཅད་མཁྱེན་པ་གཞན་ཕན་ལྷུན་གྲུབ་ཀྱི་ནག་འགྲོས་རབ་ཏུ་གསལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9009':
      image_group_id: I1KG17973
      title: ''
      total_pages: 390
      order: 1
      base_file: 9009.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
