id: P000652
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17591
  title: དཔལ་ཀུན་རིག་གི་ཆོ་ག་ཐམས་ཅད་མཁྱེན་པ་གཞན་ཕན་ལྷུན་གྲུབ་ཀྱི་ནག་འགྲོས་རབ་ཏུ་གསལ་བ།
  author: ''
  volumes:
    b124c888fa4648699cd52a2c5f48d0d9:
      image_group_id: I1KG17973
      title: ''
      volume_number: 1
      total_pages: 390
